services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1337}'
        WWWUSER: '${WWWUSER:-1337}'
        CMAKE_BUILD_TYPE: '${CMAKE_BUILD_TYPE:-Release}'
        LOCALE: '${LOCALE:-en_US}'
    image: eressea/server
    hostname: eressea
    environment:
        WWWUSER: '${WWWUSER:-1337}'
        WWWGROUP: '${WWWGROUP:-1337}'
        CMAKE_BUILD_TYPE: '${CMAKE_BUILD_TYPE:-Release}'
