require 'tests.e3.castles'
require 'tests.e3.stealth'
require 'tests.e3.spells'
require 'tests.e3.rules'
require 'tests.e3.parser'
require 'tests.e3.morale'
require 'tests.orders'
require 'tests.common'
require 'tests.magicbag'
require 'tests.process'

require 'tests.e3.fleets'
