require 'tests.shared.process'
require 'tests.shared.items'
require 'tests.shared.spells'
require 'tests.shared.storage'

require 'tests.e3.buildings'
require 'tests.e3.stealth'
require 'tests.e3.spells'
require 'tests.e3.rules'
require 'tests.e3.parser'
require 'tests.e3.morale'
require 'tests.e3.items'
require 'tests.e3.production'
require 'tests.e2.common'
