#!/usr/bin/env bash

if [ ! -e eressea.ini ]; then
  cp /usr/local/share/eressea/conf/eressea.ini .
fi

export LUA_PATH="/usr/local/share/eressea/scripts/?.lua;/usr/local/share/eressea/scripts/?/init.lua;$LUA_PATH"
export ERESSEA_INSTALL=/usr/local/share/eressea
exec eressea -i "$ERESSEA_INSTALL" "$@"
