-- new tests 2014-06-11
require 'tests.faction'
require 'tests.locale'
require 'tests.movement'
require 'tests.pool'
require 'tests.regions'
require 'tests.settings'
require 'tests.study'
require 'tests.laws'
require 'tests.bindings'
require 'tests.hunger'
