--[[
require 'tests.laws'
require 'tests.faction'
require 'tests.locale'
require 'tests.movement'
require 'tests.pool'
require 'tests.regions'
require 'tests.settings'
require 'tests.study'
require 'tests.bindings'
require 'tests.hunger'
require 'tests.transport'
require 'tests.defaults'
require 'tests.shiplanding'
require 'tests.harbor'
]]
require 'tests.economy'
