dofile('config.lua')
eressea.free_game()
pl = plane.create(0, -5, -5, 11, 11)
r = region.create(0, 0, "plain")
f = faction.create("test1@gmail.com", "human", "en")
u = unit.create(f, r, 1)
u:add_item("money", 5000)
u:add_item("horse", 1)
u:add_item("log", 5)
u = unit.create(f, r, 1)
f = faction.create("test2@gmail.com", "aquarian", "en")
u = unit.create(f, r, 1)
u:add_item("money", 5000)
u:add_item("horse", 1)
u:add_item("log", 5)
u = unit.create(f, r, 1)
r = region.create(0, -1, "mountain")
r = region.create(-1, 0, "highland")
r = region.create(-1, -1, "desert")
r = region.create(0, 1, "swamp")
r = region.create(1, 0, "glacier")
r = region.create(1, 1, "ocean")
eressea.write_game("0.dat")
eressea.export("map.json", 1)
eressea.export("world.json", 7)
