-- require 'eressea.tests.spells'
require 'eressea.tests.common'
require 'eressea.tests.stealth'
-- require 'eressea.tests.spells-e3'
-- require 'eressea.tests.spells-e2'
require 'eressea.tests.settings'
-- require 'eressea.tests.morale'
-- require 'eressea.tests.orders'
-- require 'eressea.tests.eressea'
-- require 'eressea.tests.e3a'
-- require 'eressea.tests.config'
-- require 'eressea.tests.common'
require 'eressea.tests.castles'
require 'eressea.tests.bindings'
-- require 'eressea.tests.bson'
-- require 'eressea.tests.attrib'
