#!/bin/sh
ROOT=$(pwd)
while [ ! -d $ROOT/.git ]; do
  ROOT=$(dirname $ROOT)
done

[ -z "$CC" ] && CC=clang
[ -z "$BUILD" ] && BUILD=Debug

[ -z "$JOBS" ] && JOBS=$(nproc)
DISTCC=`which distcc`
if [ ! -z "$DISTCC" ] ; then
JOBS=`distcc -j`
if [ -z "$JOBS" ] ; then
JOBS=1
elif [ $JOBS -gt 1 ] ; then
CC="$DISTCC $CC"
MAKEOPTS=-j$JOBS
fi
fi
echo "Building with CC=$CC and $JOBS jobs"

if [ ! -d $ROOT/$BUILD ]; then
  echo "cannot find build directory $BUILD in $ROOT. did you run cmake-init?"
  exit
fi

git submodule update
echo "build tolua"
cd $ROOT/tolua ; make
echo "build eressea"
cd $ROOT/$BUILD
make $MAKEOPTS && make test
cd $OLDPWD
