#!/bin/bash
set -e
test -e .env && eval $(cat .env)
BRANCH=$(git status -s -b | head -1 | cut -d\  -f 2 | sed 's/\..*//')
VERSION=$(git describe --tags --match 'v*.*.*')
echo "submitting version $BRANCH-$VERSION"
cd Debug
make clean
cov-build --dir cov-int make eressea
tar czf eressea.tgz cov-int
curl -k --form token=${COV_TOKEN} \
  --form email=enno.rehling@gmail.com \
  --form file=@eressea.tgz \
  --form version="$BRANCH-$VERSION" \
  --form description="Eressea coverity check" \
  https://scan.coverity.com/builds?project=eressea%2Fserver
