#!/bin/bash
set -euo pipefail

#IGNORE=$(find src -name "*.test.c" | awk '{ print "-i"$1 }')

#cppcheck $IGNORE -isrc/tests.c \
cppcheck --quiet --enable=warning,style,performance,portability -U_MSC_VER -UCLEANUP_CODE -UTODO \
 -UERESSEA_BUILDNO -UERESSEA_VERSION -UTEST_THREADS \
 -IcJSON -Isrc -Iclibs -Istorage src

