#!/bin/sh

FORCE=0
while getopts f o; do
  case "${o}" in
  f) FORCE=yes
  ;;
  *) usage
  ;;
  esac
done

if [ "$FORCE" != "yes" ] ; then
  DESCRIBE=$(git describe --tags)
  VERSION=$(build/eressea/eressea --version | sed -e 's/Eressea version \([^,]*\),.*/\1/')
  if [ "$VERSION" != "$DESCRIBE" ] ; then
      echo "You must buld the server before installing it"
      echo "Current build is $VERSION, source is $DESCRIBE"
      exit
  fi
  BRANCH=$(git status -s -b | head -1 | cut -d\  -f 2 | sed 's/\..*//')
  if [ "$BRANCH" != "master" ] ; then
    echo "You should only install stable versions from the master branch. Use -f to override."
    exit
  fi
fi
[ -z "$CC" ] && [ -n "$(which clang)" ] && CC="clang"
[ -z "$CC" ] && [ -n "$(which gcc)" ] && CC="gcc"
[ -z "$CC" ] && [ -n "$(which tcc)" ] && CC="tcc"
[ -z "$CC" ] && [ -n "$(which cc)" ] && CC="cc"
BIN_DIR="build"

ROOT=$(git rev-parse --show-toplevel)
PREFIX=$(dirname "$ROOT")/server
cd "$ROOT" || exit
cmake --install "$BIN_DIR" --prefix "$PREFIX"
if [ ! -e "$PREFIX/bin/backup-eressea" ] ; then
    if [ -e ~/.onedrive-cli-token ] ; then
        cd "$PREFIX" || exit
        ln -sf backup-onedrive backup-eressea
        cd - || exit
    fi
fi
