#!/bin/bash
set -euo pipefail

function usage() {
cat <<HEREDOC
usage: $0 [-f]
Use -f if you are not installing from the master branch. This is considered unsafe."
HEREDOC
exit 1
}

FORCE=0
while getopts f o; do
  case "${o}" in
  f) FORCE=yes ;;
  ?) echo "unknown option ${o}"; usage ;;
  esac
done
if [ "$FORCE" != "yes" ] ; then
  BRANCH=$(git status -s -b | head -1 | cut -d\  -f 2 | sed 's/\..*//')
  if [ "$BRANCH" != "master" ] ; then
    echo "You are in the branch $BRANCH, but you should only install stable versions from the master branch. Use -f to override."
    exit 1
  fi
fi
[ -z "${CC+x}" ] && [ -n "$(which clang)" ] && CC="clang"
[ -z "${CC+x}" ] && [ -n "$(which gcc)" ] && CC="gcc"
[ -z "${CC+x}" ] && [ -n "$(which tcc)" ] && CC="tcc"
[ -z "${CC+x}" ] && [ -n "$(which cc)" ] && CC="cc"
BIN_DIR="build"

ROOT=$(git rev-parse --show-toplevel)
PREFIX=$(dirname "$ROOT")/server
cd "$ROOT"
cmake --install "$BIN_DIR" --prefix "$PREFIX"
