#!/usr/bin/env python

import subprocess
import sys

def new_version(ver):
    subprocess.run(["git", "tag", "-f", "v" + ver], check=True)
    subprocess.run(["git", "push", "--tags", "-f"], check=True)

new_version(sys.argv[1])
