#!/bin/bash
set -euo pipefail

eval "$(luarocks path)"
ROOT=$(git rev-parse --show-toplevel)
export LUA_PATH="$ROOT/scripts/?.lua;$LUA_PATH"
BUILD="$ROOT/build"

UNIT_TESTS="$BUILD/eressea/test_eressea"
RUN_TESTS="$BUILD/eressea/eressea"
if [[ -n "${1+x}" && "$1" = "-V" ]]; then
SUPP="$ROOT/share/ubuntu-12_04.supp"
UNIT_TESTS="valgrind --quiet --suppressions=$SUPP --error-exitcode=1 --leak-check=no $UNIT_TESTS"
RUN_TESTS="valgrind --quiet --suppressions=$SUPP --error-exitcode=1 --leak-check=no $RUN_TESTS"
fi

cd "$ROOT/tests"
$UNIT_TESTS
$RUN_TESTS -v1 ../scripts/run-tests.lua
$RUN_TESTS -v1 ../scripts/run-tests-e2.lua
$RUN_TESTS -v1 ../scripts/run-tests-e3.lua
$RUN_TESTS --version
rm -rf reports orders.txt score score.alliances datum turn

cd "$OLDPWD"
