#!/bin/bash
set -e

eval $(luarocks path)
ROOT=$(git rev-parse --show-toplevel)
export LUA_PATH="$ROOT/scripts/?.lua;$LUA_PATH"
[ -z $BUILD ] && BUILD=Debug ; export BUILD

UNIT_TESTS=$ROOT/$BUILD/eressea/test_eressea
RUN_TESTS=$ROOT/$BUILD/eressea/eressea
if [ "$1" = "-V" ]; then
SUPP=$ROOT/share/ubuntu-12_04.supp
UNIT_TESTS="valgrind --quiet --suppressions=$SUPP --error-exitcode=1 --leak-check=no $UNIT_TESTS"
RUN_TESTS="valgrind --quiet --suppressions=$SUPP --error-exitcode=1 --leak-check=no $RUN_TESTS"
fi

if [ ! -e $ROOT/$BUILD ]; then
  echo "cannot find build directory $BUILD in $ROOT. did you run cmake-init?"
  exit
fi


cd $ROOT/tests
$UNIT_TESTS
$RUN_TESTS -v1 ../scripts/run-tests.lua
$RUN_TESTS -v1 ../scripts/run-tests-e2.lua
$RUN_TESTS -v1 ../scripts/run-tests-e3.lua
$RUN_TESTS --version
rm -rf reports orders.txt score score.alliances datum turn

cd $OLDWPD
