#!/bin/sh

ROOT=`pwd`

inifile() {
cd $ROOT
if [ ! -e eressea.ini ]; then
cp conf/eressea.ini .
$BUILD/iniparser/inifile eressea.ini add lua:paths lunit:scripts
fi
}

integraton_tests() {
cd tests
./write-reports.sh
./run-turn.sh
}

set -e
[ -z $BUILD ] && BUILD=Debug ; export BUILD
s/cmake-init
s/build
cd $ROOT
inifile
s/runtests

integraton_tests
