#!/bin/sh

ROOT=`pwd`

inifile() {
cd $ROOT
if [ ! -e eressea.ini ]; then
cp conf/eressea.ini .
$BUILD/tools/inifile eressea.ini add lua:paths lunit:scripts
fi
}

integration_tests() {
cd tests
./write-reports.sh
./run-turn.sh
}

cppcheck_tests() {
 cppcheck --version
 DIRS="util kernel modules races attributes triggers items tools spells"
 IGNORE=""
 for DIR in $DIRS ; do
  IGNORE="$IGNORE -i src/$DIR"
  echo "cppcheck src/$DIR"
  cppcheck --quiet -Isrc -Iclibs -Istorage -IcJSON --error-exitcode=1 "src/$DIR"
 done
 echo "cppcheck src"
 cppcheck --quiet -Isrc -Iclibs -Istorage -IcJSON --error-exitcode=1 $IGNORE src
}

set -e
[ -z $BUILD ] && BUILD=Debug ; export BUILD
# cppcheck_tests
s/cmake-init --db=sqlite
cd Debug
scan-build make
cd ../process
make
cd $ROOT
inifile
s/runtests -V
integration_tests
