#!/bin/bash

GAME=$1
TURN=$2

if [ ! -d "$ERESSEA/game-$GAME" ] ; then
  echo "No such game: $GAME"
  exit 1
fi

cd "$ERESSEA/game-$GAME" || exit

if [ -d "orders.dir.$TURN" ]; then
  echo "orders.dir.$TURN already exists"
else
  mv orders.dir "orders.dir.$TURN"
  mkdir -p orders.dir
fi
find "orders.dir.$TURN" -maxdepth 1 -type f -printf "%T+\t%p\n" | sort | cut -f2 | while read -r
do
  cat "$REPLY" >> "orders.$TURN"
done

lockfile -r3 -l120 orders.queue.lock
if [ -e orders.queue ] ; then
  mv orders.queue "orders.dir.$TURN/orders.queue"
fi
rm -f orders.queue.lock


