TARGETS = subdirs

SUBDIRS = \
  util \
  kernel \
  gamecode \
  triggers \
  items \
  attributes \
  races \
  spells \
  modules \
  eressea \
  mapper

include ../Makefile.include


## more definitions
