include ../Makefile.include

all: atoi36 namegen

atoi36: atoi36.c
	$(CC) -I.. -I../common/kernel -I../common/util $(CFLAGS) $(LDFLAGS) -o atoi36 atoi36.c

namegen:
	$(CC) -I.. -I../common/kernel -I../common/util $(CFLAGS) $(LDFLAGS) -o namegen namegen.c

